// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrljnzlngioiydiimnle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybGpuemxuZ2lvaXlkaWltbmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQxMzUsImV4cCI6MjA2MDYyMDEzNX0.52nEZ-uVgePF9Q-9Da2grxZp7NmNoyT3Ia6arrdOaTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);